version: '3'
services:
  back-end:
    build:
      context: .
      dockerfile: DockerfileBack
    image: back-end-image
    ports:
      - "4444:4444"

  front-end:
    build:
      context: .
      dockerfile: DockerfileFront
    image: front-end-image
    depends_on:
      - back-end
    ports:
      - "4200:4200"
