version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: DockerfileBack
    image: back-end-image
    networks:
      app_net:
        ipv4_address: 172.168.12.2
    ports:
      - "4444:4444"

  frontend:
    build:
      context: .
      dockerfile: DockerfileFront
    image: front-end-image
    networks:
      app_net:
        ipv4_address: 172.168.12.3
    ports:
      - "4242:4242"

networks:
  app_net:
    external:
      name: rennesgo_docker_network