version: '3'
services:
  back-end:
    build: back-end
    networks:
      localnetwork:
          ipv4_address: 10.18.1.10
  
  front-end:
    build: front-end
    ports:
    - "4242:4242"
    networks:
      localnetwork:
          ipv4_address: 10.18.1.11

  


networks:
  localnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.18.1.0/24