version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: DockerfileBack
    image: back-end-image
    ports:
      - "4444:4444"

  frontend:
    build:
      context: .
      dockerfile: DockerfileFront
    image: front-end-image
    #depends_on:
     # - back-end
    ports:
      - "4242:4242"