pipeline { 
    agent any /*{ dockerfile true }*/  
    tools { 
        nodejs 'nodejs' 
    }
    stages { 
        stage ('Git') {
            steps { git branch: 'master', url: 'https://github.com/TheHakky/RennesGo'}
        }
        stage ('Install') { //npm audit fix
            steps { sh '''
                cd front-end
                npm install
            ''' }   
        }
        stage ('Test') {
            steps {
                 sh '''
                    export CHROME_BIN=/usr/bin/chrome
                    cd front-end
                    npm run ng test --watch=false --browsers=MyChrome --code-coverage
                 '''  
            }
        }
        stage ('Lint') {
            steps { sh '''
               cd front-end
               npm run ng lint
            ''' }   
        }
        /*stage ('System Test') { //npm run protractor e2e/protractor.conf.js
            steps { sh '''
                cd front-end
                npm run e2e
                ''' }   
        }*/
        stage ('Build') {
            steps { sh '''
                cd front-end
                npm run ng build
            ''' }   
        }
        stage ('Docker Build') {
            steps {
                sh 'docker stop $(docker ps -a -q) || true'
                sh 'docker system prune -f'
                sh 'docker-compose build frontend'
            }
        }
        stage ('Docker Run') {
            steps { 
                sh 'docker-compose up --no-deps -d frontend'
            }
        }
        /*stage ('Docker Prune') {
            steps {
                sh 'docker system prune -f'
            }
        }*/
    }
}
