pipeline { 
    environment {
        registry = "thehakky/back-end"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    agent any /*{ dockerfile true }*/  
    tools { 
        maven 'maven' 
    }
    stages { 
        stage ('Git') {
            steps { git branch: 'master', url: 'https://github.com/TheHakky/RennesGo'}
        }
        stage ('Compile') {
            steps { sh 'mvn -f back-end/pom.xml clean compile' }   
        }
        stage ('Test') {
            steps { sh 'mvn -f back-end/pom.xml test' }   
        }
        stage ('Package') {
            steps { sh 'mvn -f back-end/pom.xml package' }   
        }
        stage ('Install') {
            steps { /*echo 'TODO install step'*/ sh 'mvn -f back-end/pom.xml install' }   
        }
        /*stage ('Docker Build') {
            steps { 
                //script { //docker rmi -f "$(docker stop $(docker ps -q --filter ancestor=back-end-image))"
                sh 'docker-compose build back-end'
                //}
            }
        }
        stage ('Docker Run') {
            steps { 
                //script { 
                sh 'docker-compose up --detach back-end'
                //}
            }
        }
        stage ('Docker Prune') {
            steps { 
                //script { 
                sh 'docker system prune -f'
                //}
            }
        }*/
    }
}
