pipeline { 
    agent any   
    tools { 
        maven 'maven' 
    }
    stages { 
        stage ('Git') {
            steps { git branch: 'master', url: 'https://github.com/TheHakky/RennesGo'}
        }
        stage ('Compile') {
            steps { sh 'mvn -f back-end/pom.xml clean compile' }   
        }
        stage ('Test') {
            steps { sh 'mvn -f back-end/pom.xml test' }   
        }
        stage ('Package') {
            steps { sh 'mvn -f back-end/pom.xml package' }   
        }
        stage ('Install') {
            steps { sh 'mvn -f back-end/pom.xml install' }   
        }
        stage ('Docker Build') {
            steps { 
                //script { //docker rmi -f "$(docker stop $(docker ps -q --filter ancestor=back-end-image))"
                sh 'chmod +x back-end/network.sh'
                sh 'back-end/network.sh rennesgo_docker_network 172.168.12.'
                sh 'docker stop back-endpipeline_backend_1 || true'
                sh 'docker-compose build backend'
                //}
            }
        }
        stage ('Docker Run') {
            steps { 
                sh 'docker-compose up --no-deps -d backend'
            }
        }
        stage ('Docker Prune') {
            steps { 
                sh 'docker system prune -f'
            }
        }
    }
}
